# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180323_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'image'), (1, 'Banner image'), (2, 'Newsfeed image')], default=0),
        ),
    ]
