# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180323_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'image'), (1, 'Banner image'), (2, 'Newsfeed image'), (3, 'Newsfeed Banner image')], default=0),
        ),
    ]
