# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180326_0642'),
        ('customer', '0005_auto_20180326_0541'),
    ]

    operations = [
    ]
