# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_merge_20180326_1004'),
        ('customer', '0006_merge_20180326_1007'),
    ]

    operations = [
    ]
