# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180403_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvite',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customerinvite',
            name='invite_type',
            field=models.IntegerField(choices=[(0, 'SMS'), (1, 'EMAIL')]),
        ),
    ]
