# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20180404_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvite',
            name='invite_type',
            field=models.IntegerField(choices=[(0, 'SMS'), (1, 'EMAIL')], default=0),
        ),
    ]
