# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20180404_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinvite',
            old_name='refferal_code',
            new_name='referral_code',
        ),
    ]
