# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20180404_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvite',
            name='referral_code',
        ),
    ]
