# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_membershiplevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstatus',
            name='status_card_level',
        ),
    ]
