# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0004_remove_shopstatus_status_card_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_needed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user_id', to=settings.AUTH_USER_MODEL)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.MembershipLevel')),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
