# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_statuslevel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslevel',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
