# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_auto_20180301_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslevel',
            name='priority',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
