# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_auto_20180301_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.CharField(max_length=20)),
                ('message_content', models.CharField(choices=[('Request From Customer For Delivery', 'Request From Customer For Delivery')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
