# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_pushmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='message_content',
            field=models.CharField(max_length=255),
        ),
    ]
