# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_auto_20180315_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='dev_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
