# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_auto_20180321_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseshopcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_category'),
        ),
    ]
