# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_auto_20180323_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
