# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('qr_code', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=1046)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tamper_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('modified_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tamper_modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cutomer_type', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=512, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=512, null=True)),
                ('location1', models.CharField(blank=True, max_length=512, null=True)),
                ('pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.CharField(max_length=512)),
                ('number_of_bags', models.IntegerField(blank=True, null=True)),
                ('stored_location_id', models.IntegerField(blank=True, null=True)),
                ('location2', models.CharField(blank=True, max_length=512, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_baggage.CustomerBag')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1046)),
                ('category', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zone_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('modified_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zone_modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
    ]
