# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0004_bagtohandlermapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagtohandlermapping',
            name='baggage_id',
        ),
        migrations.RemoveField(
            model_name='bagtohandlermapping',
            name='created_user_id',
        ),
        migrations.RemoveField(
            model_name='bagtohandlermapping',
            name='handler_id',
        ),
        migrations.RemoveField(
            model_name='bagtohandlermapping',
            name='modified_user_id',
        ),
        migrations.DeleteModel(
            name='BagToHandlerMapping',
        ),
    ]
