# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0007_location_physical_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
