# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0008_location_capacity_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='total_shelves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
