# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0009_location_total_shelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbag',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_baggage.Location'),
        ),
    ]
