# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0010_customerbag_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='category',
        ),
    ]
