# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0012_auto_20180309_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbag',
            name='customer_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
