# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0013_customerbag_customer_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbag',
            name='customer_requested_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
