# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_baggage', '0016_customerbag_customer_requested_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='alias',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
