# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('api_user', '0004_auto_20180124_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
