# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_auto_20180208_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
