# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_addressforuser_customerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
    ]
