# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0009_customerdetail_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='created_on',
            new_name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='status',
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
