# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0010_auto_20180226_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
