# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0011_auto_20180226_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='referral_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
