# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-03 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0011_auto_20180226_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
