# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0012_customerdetail_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='referred_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
