# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0012_customerdetail_address'),
        ('api_user', '0013_auto_20180404_0650'),
    ]

    operations = [
    ]
