# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_zone', '0002_auto_20180206_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonetozonemanagermapping',
            options={},
        ),
    ]
