# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_zone', '0004_remove_zonetozonemanagermapping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonetozonemanagermapping',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managers', to='api_baggage.Location'),
        ),
    ]
