# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180323_0851'),
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='images',
            field=models.ManyToManyField(null=True, to='customer.ImageGallery'),
        ),
    ]
