# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_newsfeed_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='images',
            field=models.ManyToManyField(blank=True, to='customer.ImageGallery'),
        ),
    ]
