# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20180323_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='category',
            field=models.CharField(blank=True, choices=[('Discount', 'Discount'), ('Event', 'Event')], max_length=20, null=True),
        ),
    ]
