# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnActionDetail',
            fields=[
                ('action_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('validity_type', models.IntegerField(choices=[(1, 'DATE'), (2, 'PERIOD')], default=1)),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('validity_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='burn_action_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='burn_action_modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BurnTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burned_points', models.FloatField()),
                ('validity_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('burned_action', models.ForeignKey(blank=True, db_column='action_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='burned_user_id', to='api_ern_burn.BurnActionDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='burned_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErnActionDetail',
            fields=[
                ('action_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('validity_type', models.IntegerField(choices=[(1, 'DATE'), (2, 'PERIOD')], default=1)),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('validity_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ern_action_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ern_action_modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErnBurnTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_points', models.FloatField()),
                ('transfer_points', models.FloatField()),
                ('balance_points', models.FloatField()),
                ('transaction_type', models.IntegerField(choices=[(1, 'EARN'), (2, 'BURN')], default=1)),
                ('transaction_id', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ern_burn_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErnTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erned_points', models.FloatField()),
                ('validity_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('erned_action', models.ForeignKey(blank=True, db_column='action_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='erned_user_id', to='api_ern_burn.ErnActionDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='erned_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EurnBurnSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_days', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setting_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setting_modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLevel',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('points_needed', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user_id', to=settings.AUTH_USER_MODEL)),
                ('modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ern_points', models.FloatField()),
                ('total_burn_points', models.FloatField()),
                ('balance_points', models.FloatField()),
                ('expire_points', models.FloatField(blank=True, null=True)),
                ('erned_amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='summary_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
