# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ernburntransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Earn', 'EARN'), ('Burn', 'BURN')], max_length=5, null=True),
        ),
    ]
