# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_ern_burn', '0003_remove_summary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='earn_burn_summary', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
