# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0005_auto_20180227_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burntransaction',
            name='burned_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ernburntransaction',
            name='balance_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ernburntransaction',
            name='opening_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ernburntransaction',
            name='transfer_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='erntransaction',
            name='erned_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='statuslevel',
            name='points_needed',
            field=models.FloatField(default=0.0),
        ),
    ]
