# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0006_auto_20180227_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnactiondetail',
            name='validity_type',
            field=models.CharField(choices=[('Date', 'Date'), ('Period', 'Period')], default='Date', max_length=6),
        ),
        migrations.AlterField(
            model_name='ernactiondetail',
            name='validity_type',
            field=models.IntegerField(choices=[('Date', 'Date'), ('Period', 'Period')], default=1),
        ),
    ]
