# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0007_auto_20180227_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ernactiondetail',
            name='validity_type',
            field=models.CharField(choices=[('Date', 'Date'), ('Period', 'Period')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ernburntransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Earn', 'Earn'), ('Burn', 'Burn')], max_length=5, null=True),
        ),
    ]
