# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0011_summary_membership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErnActionDetail',
            new_name='EarnActionDetail',
        ),
        migrations.RenameModel(
            old_name='ErnBurnSettings',
            new_name='EarnBurnSettings',
        ),
        migrations.RenameModel(
            old_name='ErnBurnTransaction',
            new_name='EarnBurnTransaction',
        ),
        migrations.RenameModel(
            old_name='ErnTransaction',
            new_name='EarnTransaction',
        ),
    ]
