# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_auto_20180321_0853'),
        ('api_ern_burn', '0012_auto_20180322_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnactiondetail',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Shop'),
        ),
    ]
