# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0013_earnactiondetail_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnactiondetail',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='earnactiondetail',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
