# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0014_auto_20180323_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnactiondetail',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earn_coupons', to='base_app.Shop'),
        ),
    ]
