# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0015_auto_20180323_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnactiondetail',
            name='terms_and_conditions',
            field=models.TextField(null=True),
        ),
    ]
