# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0017_earnactiondetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnactiondetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_burns'),
        ),
        migrations.AddField(
            model_name='burnactiondetail',
            name='terms_and_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='earnactiondetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_earns'),
        ),
    ]
