# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0024_earnactiondetail_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='burntransaction',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='burntransaction',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
