# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_ern_burn', '0025_auto_20180406_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='burntransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burntransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='burntransaction',
            name='purchased',
            field=models.BooleanField(default=True),
        ),
    ]
